### ISSUE TITLE
Quotes on Asking Questions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#21]
Asking questions is _essential_ to learning and progress in work and _life_. 
We all ask questions when we are young and curious about the world.
Spend a few minutes with a 2-5 year old child and you'll see how many questions they ask!
Sadly, some adults lose their curiosity and _stop_ asking questions.

## "_Successful people ask better questions, and as a result, they get better answers_." ~ Tony Robbins

# Todo

Read through quotes about asking questions and extract the best ones.

+ [ ] https://www.lifehack.org/articles/productivity/36-quotes-from-successful-people-about-the-wisdom-asking-questions.html
+ [ ] https://www.awakenthegreatnesswithin.com/35-inspirational-quotes-on-questions
+ [ ] https://www.brainyquote.com/topics/asking-questions-quotes
