### ISSUE TITLE
Quotes on Ideas

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#51]
There are _many_ good quotes on ideas. We need to filter and record the best ones. 💡 

# Todo

Comb through all the popular sites that list quotes and capture the ones we find inspiring _action_:

Here's a starting point:
+ [ ] https://www.goodreads.com/quotes/tag/ideas ⭐⭐⭐ (_ordered by community votes_)
+ [ ] http://www.ideachampions.com/weblogs/archives/2010/11/50_very_awesome.shtml ⭐⭐  (_pre-filtered_)
+ [ ] https://www.brainyquote.com/topics/ideas-quotes ⭐ (_ordered by editorial_)
+ [ ] https://ineedmotivation.com/45-unforgettable-quotes-about-ideas/
+ [ ] https://www.forbes.com/quotes/theme/ideas/
+ [ ] https://www.virgin.com/branson-family/richard-branson-blog/my-top-10-quotes-ideas ⭐ (_chosen by Richard_)

**Note**:  all quotes must have a **source** and tags otherwise they are invalid. We don't accept any quotes that are "anonymous" or "Buddha" even if they are _really_ good.

**Comment by nelsonic** [comment]
First pass:

```json
  {
    "author": "Victor Hugo",
    "source": "https://www.goodreads.com/quotes/2302",
    "tags": "idea, ideas, time",
    "text": "No army can withstand the strength of an idea whose time has come."
  },
  {
    "author": "Ursula Leguin",
    "source": "https://www.goodreads.com/quotes/1260096",
    "tags": "creative, creativity, child",
    "text": "The creative adult is the child who survived."
  },
  {
    "author": "Marie Curie",
    "source": "https://www.goodreads.com/quotes/45949",
    "tags": "idea, ideas, curious, curiosity, people, gossip",
    "text": "Be less curious about people and more curious about ideas."
  },
  {
    "author": "Sue Grafton",
    "source": "https://www.goodreads.com/quotes/6862779",
    "tags": "idea, ideas, execution",
    "text": "Ideas are easy. It's the execution of ideas that really separates the sheep from the goats."
  },
```

**Comment by dannya** [comment]
Implemented https://github.com/dwyl/quotes/issues/51#issuecomment-907814604 in commit referenced above - some were already included.
