### ISSUE TITLE
Montessori Quotes

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#55]
I've been reading "The Absorbent Mind" by Maria Montessori. There are _many_ good passages but they aren't really _quotes_ ... we need need to collate a few good quotes on her education philosophy/pedagogy and add them to our list!

Starting point: 🔍 

+ [ ] https://mommybabyplay.com/maria-montessori-quotes/ - only add the quotes we can find reliable sources for!
+ [ ] https://www.goodreads.com/author/quotes/34106.Maria_Montessori

# Todo ✅ 

+ [ ] Add 10 - 20 quotes we find relevant/inspiring 📝 
+ [ ] Create a PR 🚀 
+ [ ] Ship the new version of the package to NPM and Hex.pm 📦

**Comment by nelsonic** [comment]
https://applemontessorischools.com/montessori-quotes/
