### ISSUE TITLE
Sleep Quotes

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#58]
Sleep is the single most important daily activity. It is the cornerstone of a healthy and effective life.

# Todo

+ [ ] Scour through the internet for a few (e.g. 10) good quotes on sleep. 
  Starting point:
  + [ ] Popular: https://www.goodreads.com/quotes/tag/sleep
  + [ ] https://casper.com/blog/sleep-quotes/ fitting for a mattress company. 😉 
  + [ ] https://parade.com/1158475/kelseypelzer/sleep-quotes/
  + [ ] https://restonic.com/blog/quotes-better-sleep-2546
  + [ ] https://www.sensacalm.com/blogs/news/best-sleep-quotes
  + [ ] https://www.brainyquote.com/topics/sleep-quotes

I think this one might be tricky because a _lot_ of the quotes are about _not_ sleeping. e.g:

### "_I'll sleep when I'm dead._" ~ Warren Zevon

The science tells us that avoiding sleep will _cause_ you die younger. So it's a self-fulfilling prophesy! 

And some _imply_ wakefulness is better than sleeping: 

### “_You know you're in love when you can't fall asleep <br />because reality is finally better than your dreams_.” <br />~ Dr. Seuss

Don't get me wrong, I _love_ this quote and can totally empathise with it. 😍 
However I'm not sure that it's _inspiring_... 🤔 
And it might be the _opposite_ of _promoting_ sleep;
It might tell people that it's "OK" to stay awake because reality is better than dreaming [sleeping] ... 
Thoughts?

I think these are good:

### "_A well spent day brings happy sleep._" ~ Leonardo da Vinci 
Seems legit: https://www.goodreads.com/quotes/74114-as-a-well-spent-day-brings-happy-sleep-so-life

### "_Each night, when I go to sleep, I die. <br />And the next morning, when I wake up, I am reborn._" <br />~ Mahatma Gandhi
