### ISSUE TITLE
Stoic Quotes

### ISSUE THREAD

**Issue by nelsonic** [dwyl/quotes#61]
## "_The things you think about determine the quality of your mind._” ~ Marcus Aurelius

i.e. if you're constantly thinking about what the media want you to think about, e.g. COVID, Celebrity Gossip, sports or short-term politics, your mind won't be very good ... 🙄 

# Todo 

+ [ ] Collect a few (e.g. 20) quotes
+ [ ] Add them to the `quotes.json` file with the appropriate source and tags.
+ [ ] Create a pull request 

## Starting point for quotes:

+ [ ] https://www.goodreads.com/quotes/tag/stoicism
+ [ ] https://medium.com/stories-by-aurora-e/20-stoic-quotes-that-will-motivate-and-inspire-you-bfb4fc7fc660
+ [ ] https://dailystoic.com/stoic-quotes/

**Comment by bryanmanio** [comment]
There are a bunch more here as well - https://mindofastoic.com/stoic-quotes
